### PR TITLE
LAM transforms in ectrans

### PR DESCRIPTION
**Pull request by ddegrauwe**
Include LAM (bifourier) spectral transforms in ectrans.

Remarks:
* activation is done with cmake option -DENABLE_ETRANS (default OFF)
* biperiodization routines (biper) are also included
* most test programs (aatestprog, biper) are omitted here, but can be kept in IAL. A benchmark program ectrans-lam-benchmark is included.
* no separate library or include directories are created for LAM transforms. These are included in libtrans_dp.a (or libtrans_sp.a, libtrans_dp.so, libtrans_sp.so)
* tested with IAL cy49t2 (https://github.com/ddegrauwe/IAL/tree/daand_49t2_ectrans_lam)

### CODE REVIEW

**Comment by AlexandreMary** [comment]
Hi Daan,
(cc @walidchikhi for the FA/epygram part)
just having a look at that now, in sight of CY50 or 50T1.
I tried some tests with it (+ your IAL branch) and I face an issue with ELLIPS/ELLIPS64 that you moved in there, but that is also used by FA (FACADI), in turn used by some programs that we don't link with ectrans at the moment (lfitools, PGD, PREP).
So I think the best would probably be to move ellips.h, ellips.F90 & ellips64.F90 in Fiat ?
What do you think ?
If you agree, could you do that and provide a Fiat branch that would complement your ectrans & IAL branches ?
Thanks
Alexandre

**Comment by AlexandreMary** [comment]
Apart from that (hacking Davai to get the other executables), seems to work fine ! LAM forecasts are bit-repro :+1:

**Comment by ddegrauwe** [comment]
Okay, good suggestion to move ellips into fiat. I'll make the necessary modifications.

**Comment by ddegrauwe** [comment]
I moved the ellips routines to fiat.

I created a new [pull request](https://github.com/ACCORD-NWP/ectrans/pull/4) for ectrans, along with [one](https://github.com/ACCORD-NWP/fiat/pull/6) for fiat and one for IAL.

This solves the compilation of lfitools, but it seems PGD and PREP still require linking to ectrans (since they link to arpifs, which depends on ectrans).

**Comment by AlexandreMary** [comment]
OK thanks !
For PGD/PREP, I think in theory they shouldn't link arpifs anymore... I'll have a look.

**Pull request merged**
